src/backend/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

src/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('votes/<int:pk>/', views.UpdateView.as_view(), name='update')
]

src/polls/models.py
from django.db import models

from django.conf import settings
from polls.choices import *


def filter_votes(vote):
    return vote.vote_value


class Poll(models.Model):

    def complexity(self):
        votes = list(map(filter_votes, self.vote_set.all()))
        return round(sum(votes) / len(votes), 2) if len(votes) else "Not Set"

    poll_title = models.CharField(max_length=200)
    poll_description = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='publisher', on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True, blank=True)


class Vote(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='voter', on_delete=models.CASCADE)
    vote_value = models.FloatField(default=0, choices=COMPLEXITY)
    pub_date = models.DateTimeField(auto_now_add=True, blank=True)

src/polls/forms.py
from django import forms
from polls.choices import *


class VotingForm(forms.Form):
    vote = forms.ChoiceField(choices=COMPLEXITY, label="", initial='', widget=forms.Select(), required=True)


class PollForm(forms.Form):
    title = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )
    description = forms.CharField(
            widget=forms.Textarea(
                attrs={"class": "form-control"}
                )
            )

src/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormMixin

from .forms import VotingForm, PollForm
from .models import Poll, Vote


class IndexView(LoginRequiredMixin, generic.TemplateView, FormMixin):
    template_name = 'polls/index.html'
    form_class = PollForm
    success_url = './'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['polls_list'] = Poll.objects.order_by('-pub_date')
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        user = self.request.user
        poll_title = form.cleaned_data.get("title")
        poll_description = form.cleaned_data.get("description")
        Poll.objects.create(user=user, poll_title=poll_title, poll_description=poll_description)
        return super().form_valid(form)


class DetailView(LoginRequiredMixin, generic.DetailView, FormMixin):
    model = Poll
    template_name = 'polls/detail.html'
    form_class = VotingForm
    success_url = './'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        context['voted'] = self.user_voted()
        return context

    def user_voted(self):
        poll = self.get_object()
        user = self.request.user
        votes = poll.vote_set.all()
        for vote in votes:
            if vote.user == user:
                return True
        return False

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        poll = self.get_object()
        user = self.request.user
        vote_value = form.cleaned_data.get("vote")
        Vote.objects.create(user=user, poll=poll, vote_value=vote_value)
        return super().form_valid(form)


class UpdateView(LoginRequiredMixin, generic.DetailView, FormMixin):
    model = Vote
    template_name = 'polls/update.html'
    form_class = VotingForm

    def get_success_url(self):
        vote = self.get_object()
        return '/polls/' + str(vote.poll.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        form = self.get_form()
        vote = self.get_object()
        if form.is_valid() and self.request.user == vote.user:
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        vote = self.get_object()
        vote_value = form.cleaned_data.get("vote")
        Vote.objects.filter(pk=vote.id).update(vote_value=vote_value)
        return super().form_valid(form)

src/polls/templates/polls/detail.html
{% block content %}
<h1>Poll: {{ poll.poll_title }}</h1>
<p><b>Description:</b> {{ poll.poll_description }}</p>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if poll.vote_set.all %}
<h3>Voters:</h3>
<ul id='voters'>

    {% for vote in poll.vote_set.all %}

    <li>
        {{ vote.user }} voted {{ vote.vote_value }}
        {% if vote.user == user %}
        <a href="{% url 'polls:update' vote.id %}">Change vote</a>
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No votes yet.</p>
{% endif %}
<h3>Complexity: {{poll.complexity}}</h3>
{% if voted %}
<p><b>You've already voted</b></p>
{% else %}
<form id='form' method='POST'> {% csrf_token %}
    {{form.as_p }}
    <input type='submit' class='btn btn-primary'/>
</form>
{% endif %}

{% endblock %}

src/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<h1>Current Polls</h1>

{% if polls_list %}
    <ul>
    {% for poll in polls_list %}
        <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.poll_title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<h1>Create New Poll</h1>
<form id='form' method='POST'> {% csrf_token %}
    {{form.as_p }}
    <input type='submit' class='btn btn-primary'/>
</form>

src/polls/templates/polls/update.html
<h1>Update Vote</h1>

<form id='form' method='POST'> {% csrf_token %}
    {{form.as_p }}
    <input type='submit' class='btn btn-primary'/>
</form>

src/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Backend Test{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

src/templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}